# Generated by Django 4.2.3 on 2023-07-20 07:34

import CommRequests.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Labs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("CSec", "Cyber Security"),
                            ("CComp", "Cloud Computing"),
                            ("IT", "Information Technology"),
                            ("SysArch", "System Architect"),
                        ],
                        default="CSec",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("project_name", models.CharField(max_length=30)),
                ("domain_of_project", models.CharField(max_length=20)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=CommRequests.models.upload_file
                    ),
                ),
            ],
        ),
    ]
