# Generated by Django 4.2.3 on 2023-07-20 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("CommRequests", "0001_initial"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requests",
            name="recipients",
            field=models.ManyToManyField(
                limit_choices_to={"is_staff": False},
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requests",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labs",
            name="head",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_head",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labs",
            name="members",
            field=models.ManyToManyField(
                related_name="lab_members", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="labs",
            name="projects",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="projects", to="main.project"
            ),
        ),
    ]
